@MusteriDbWebApi_HostAddress = http://localhost:5276

POST {{MusteriDbWebApi_HostAddress}}/api/musteriler
Content-Type: application/json

{
  "firstName": "Api",
  "lastName": "Test",
  "email": "api.test@example.com"
}